name: Deploy webapp

on:
  push:


jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint and build code
        working-directory: ./webapp
        run: |
          npm install
          npm run lint
          npm run build
