name: Deploy webapp

on:
  push:


jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cd webapp
      - run: npm install
      - run: npm run lint
      - run: npm run build
